export const projectsData = [
  {
    name: "Modelisation Rhino avec IHM en VR",
    description: "Modelisation Rhino avec IHM en VR \u2014 C#, Python, Unity(Unity3D, XR Toolkit), Rhino 8, Websockets.",
    github_link: "https://github.com/RacimZz/Rhino-VR",
    Sujet: "https://drive.google.com/drive/folders/1dvyUFiwMuhgVZudEV7qf73dHN3fY7AeW?usp=drive_link",
    tech: ["C#", "Python", "Unity", "XR Toolkit", "Rhino 8", "Websockets"],
  },
  {
    name: "ChatBot",
    description: "ChatBot \u2014 Python, Flask, Google Gemini API, OpenAI Transformers, dotenv.",
    github_link: "https://github.com/RacimZz/Chatbot",
    Sujet: "https://ai.google.dev/gemini-api/docs/models/gemini?hl=fr#gemini-1.5-flash",
    tech: ["Python", "Flask", "Google Gemini API", "OpenAI Transformers", "dotenv"],
  },
  {
    name: "AI-Powered Celebrity Guesser",
    description: "AI-Powered Celebrity Guesser \u2014 Python, Gradio, Wikipedia API, Google Gemini API, dotenv.",
    github_link: "https://github.com/RacimZz/Akinator_IA",
    Sujet: "https://ai.google.dev/gemini-api/docs/models/gemini?hl=fr#gemini-1.5-flash",
    tech: ["Python", "Gradio", "Wikipedia API", "Google Gemini API", "dotenv"],
  },
  {
    name: "Tetravex-SAT Solver",
    description: "Tetravex-SAT Solver \u2014 OCaml, C, Python, Pygame, DIMACS CNF.",
    github_link: "https://github.com/RacimZz/CNF_SAT",
    Sujet: "https://drive.google.com/file/d/1N2bNN1DUwovy0mzkWGgq-F2EeJnlyB3I/view?usp=drive_link",
    tech: ["OCaml", "C", "Python", "Pygame", "DIMACS CNF"],
  },
  {
    name: "Interpr\u00e9teur ARM",
    description: "Interpr\u00e9teur ARM \u2014 C, Assembleur (ARM), AST, Makefile.",
    github_link: "https://github.com/RacimZz/ARM_Interpreter",
    Sujet: "https://developer.arm.com/documentation/101458/2404/Get-started/Arm-C-C---Compiler",
    tech: ["C", "Assembleur", "ARM", "AST", "Makefile"],
  },
  {
    name: "Automate probabiliste de l\u2019\u00e9lecteur (analyse Markovienne + simulations 1D/2D)",
    description: "Automate probabiliste de l\u2019\u00e9lecteur (analyse Markovienne + simulations 1D/2D) \u2014 Python, LaTeX (Beamer), Cha\u00eenes de Markov, Automates cellulaires probabilistes, Simulations Monte-Carlo.",
    github_link: "https://github.com/RacimZz/probabilistic-voter-model",
    Sujet: "https://github.com/RacimZz/probabilistic-voter-model/blob/main/sujet-automate.pdf",
    tech: ["Python", "LaTeX", "Beamer", "Cha\u00eenes de Markov", "Automates cellulaires probabilistes", "Simulations Monte-Carlo"],
  },
  {
    name: "Classification spectrale non supervis\u00e9e",
    description: "Classification spectrale non supervis\u00e9e \u2014 R, FisherEM, bash, clusters de calculs.",
    github_link: "https://github.com/RacimZz/FisherEM_ML",
    Sujet: "https://drive.google.com/file/d/1MmdLHnPcUQzCMysXC_RngB3rsTBKuE_D/view?usp=drive_link",
    tech: ["R", "FisherEM", "bash", "HPC"],
  },
  {
    name: "GEMINI : une approche neuronale pour le clustering de spectres \u2013 Analyse et visualisations",
    description: "GEMINI : une approche neuronale pour le clustering de spectres \u2013 Analyse et visualisations \u2014 Python (Gemclus Package), bash, Json, clusters de calculs.",
    github_link: "https://github.com/RacimZz/Gemclus_DeepLearning",
    Sujet: "https://drive.google.com/file/d/1MmdLHnPcUQzCMysXC_RngB3rsTBKuE_D/view?usp=drive_link",
    tech: ["Python", "Gemclus Package", "bash", "Json", "HPC"],
  },
  {
    name: "Calculatrice en syntaxe infixe \u2013 Parser LL(1) avec grammaire attribu\u00e9e et rattrapage d\u2019erreurs",
    description: "Calculatrice en syntaxe infixe \u2013 Parser LL(1) avec grammaire attribu\u00e9e et rattrapage d\u2019erreurs \u2014 Python, Th\u00e9orie des Langages, Analyse LL(1), Grammaire Attribu\u00e9e, Panic-Mode Error Recovery.",
    github_link: "https://github.com/RacimZz/TL",
    Sujet: "https://drive.google.com/file/d/1YtKbj1qFuOmU0uowhAGUkYCdAtuvUzwj/view?usp=drive_link",
    tech: ["Python", "Th\u00e9orie des Langages", "Analyse LL", "1", "Grammaire Attribu\u00e9e", "Panic-Mode Error Recovery"],
  },
  {
    name: "G\u00e9n\u00e9rateur de mots de passe s\u00e9curis\u00e9",
    description: "G\u00e9n\u00e9rateur de mots de passe s\u00e9curis\u00e9 \u2014 Python, Tkinter.",
    github_link: "https://github.com/RacimZz/random_password",
    Sujet: "https://www.mathweb.fr/euclide/2020/12/12/generateur-de-mots-de-passe-en-python/",
    tech: ["Python", "Tkinter"],
  },
  {
    name: "OCaml : Dames chinoises",
    description: "OCaml : Dames chinoises \u2014 OCaml.",
    github_link: "https://github.com/RacimZz/OCAML_project",
    Sujet: "https://drive.google.com/file/d/11N2cGvesSMDWV4-cmkNjecEpGCIk_GKj/view?usp=drive_link",
    tech: ["OCaml"],
  },
  {
    name: "ProjectCOW",
    description: "ProjectCOW \u2014 C, Shell.",
    github_link: "https://github.com/RacimZz/ProjectCOW",
    tech: ["C", "Shell"],
  },
  {
    name: "Tours de Hanoie",
    description: "Tours de Hanoie \u2014 Python (turtle, Tkinter).",
    github_link: "https://github.com/RacimZz/Hanoie_tower",
    Sujet: "https://drive.google.com/file/d/1QGO5sBPu-g3IbTLPohbZWFjj2jbrtRJ7/view?usp=drive_link",
    tech: ["Python", "turtle", "Tkinter"],
  },
  {
    name: "Transformation et D\u00e9tection de Contours via Mod\u00e8les Diff\u00e9rentiels",
    description: "Transformation et D\u00e9tection de Contours via Mod\u00e8les Diff\u00e9rentiels \u2014 Python, NumPy, SciPy, Matplotlib.",
    github_link: "https://github.com/RacimZz/traitement_image",
    Sujet: "https://drive.google.com/drive/folders/1CvVgse207-Avk4UTIHCDsI7BJjbXzEvu?usp=drive_link",
    tech: ["Python", "NumPy", "SciPy", "Matplotlib"],
  },
  {
    name: "D\u00e9tection de Fraude Documentaire",
    description: "D\u00e9tection de Fraude Documentaire \u2014 Python, OpenCV, Tesseract, scikit-learn, TensorFlow.",
    github_link: "https://github.com/RacimZz/Detection_de_fraude",
    Sujet: "https://sites.google.com/view/aide-python/applications/traitements-et-analyses-dimages",
    tech: ["Python", "OpenCV", "Tesseract", "scikit-learn", "TensorFlow"],
  },

];
